### ISSUE TITLE
KeyError: 'releaseDate'

### ISSUE THREAD

**Issue by gwax** [gwax/mtg_ssm#1]
Due to an upstream data issue in mtgjson, the application crashes with:

```
Traceback (most recent call last):
  File "/home/waksman/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/waksman/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/waksman/git/mtg_ssm/mtg_ssm/manager.py", line 104, in <module>
    main()
  File "/home/waksman/git/mtg_ssm/mtg_ssm/manager.py", line 100, in main
    process_files(args)
  File "/home/waksman/git/mtg_ssm/mtg_ssm/manager.py", line 69, in process_files
    coll = build_collection(args.data_path, args.include_online_only)
  File "/home/waksman/git/mtg_ssm/mtg_ssm/manager.py", line 64, in build_collection
    mtgjsondata, include_online_only=include_online_only)
  File "/home/waksman/git/mtg_ssm/mtg_ssm/mtg/collection.py", line 46, in __init__
    self.load_mtg_json(mtg_json_data, include_online_only)
  File "/home/waksman/git/mtg_ssm/mtg_ssm/mtg/collection.py", line 53, in load_mtg_json
    card_set = models.CardSet(self, set_data)
  File "/home/waksman/git/mtg_ssm/mtg_ssm/mtg/models.py", line 94, in __init__
    set_data['releaseDate'], '%Y-%m-%d').date()
```

**Comment by gwax** [comment]
This is caused by lsmoura/mtgjson#157

**Comment by gwax** [comment]
As of c3f46f91ad1287f54b1a45f253224d5e56a51814 there is a hack in place to work around this issue. I will keep it open until mtgjson fixes it and the hack is removed.
