### ISSUE TITLE
Failure to build new sheet, Invalid enum 'thick'

### ISSUE THREAD

**Issue by Valejacobo** [gwax/mtg_ssm#42]
New installation from pip3, after trying to create a new spreadsheet, it returns the following error:

    Reading data from scryfall
    Fetched https://api.scryfall.com/bulk-data
    Fetched https://api.scryfall.com/sets
    Fetched https://api.scryfall.com/migrations
    Fetched https://api.scryfall.com/migrations?page=2
    Fetched https://data.scryfall.io/default-cards/default-cards-20230509090726.json
    Traceback (most recent call last):
      File "/Users/valejacobo/Library/Python/3.9/bin/mtg-ssm", line 8, in <module>
        sys.exit(main())
      File "/Users/valejacobo/Library/Python/3.9/lib/python/site-packages/mtg_ssm/ssm.py", line 290, in main
        oracle = get_oracle(
      File "/Users/valejacobo/Library/Python/3.9/lib/python/site-packages/mtg_ssm/ssm.py", line 195, in get_oracle
        scrydata = fetcher.scryfetch()
      File "/Users/valejacobo/Library/Python/3.9/lib/python/site-packages/mtg_ssm/scryfall/fetcher.py", line 77, in scryfetch
        cards_data = msgspec.json.decode(
    msgspec.ValidationError: Invalid enum value 'thick' - at `$[50022].frame_effects[1]`

Adding the ScryFrameEffect 'thick' should fix it.

**Comment by gwax** [comment]
This should be resolved by #45 now and released as version 2.6.2
