### ISSUE TITLE
Cannot create empty collection DB (scryfall data change)

### ISSUE THREAD

**Issue by TonyRoomZ** [gwax/mtg_ssm#56]
When using version 2.6.7 I get the following error:
Looks like scryfall has made another underlying data change...

```
🟢 ❯ mtg-ssm --separate-promos create collection.xlsx
Reading data from scryfall
Fetched https://api.scryfall.com/bulk-data [CACHED]
Fetched https://api.scryfall.com/sets [CACHED]
Fetched https://api.scryfall.com/migrations [CACHED]
Fetched https://api.scryfall.com/migrations?page=2 [CACHED]
Fetched https://api.scryfall.com/migrations?page=3 [CACHED]
Fetched https://api.scryfall.com/migrations?page=4 [CACHED]
Fetched https://api.scryfall.com/migrations?page=5 [CACHED]
Fetched https://api.scryfall.com/migrations?page=6 [CACHED]
Fetched https://api.scryfall.com/migrations?page=7 [CACHED]
Fetched https://data.scryfall.io/default-cards/default-cards-20240324210707.json [CACHED]
Traceback (most recent call last):
  File "/home/tony/.local/bin/mtg-ssm", line 8, in <module>
    sys.exit(main())
  File "/home/tony/.local/lib/python3.10/site-packages/mtg_ssm/ssm.py", line 284, in main
    oracle = get_oracle(
  File "/home/tony/.local/lib/python3.10/site-packages/mtg_ssm/ssm.py", line 189, in get_oracle
    scrydata = fetcher.scryfetch()
  File "/home/tony/.local/lib/python3.10/site-packages/mtg_ssm/scryfall/fetcher.py", line 78, in scryfetch
    cards_data = msgspec.json.decode(_fetch_endpoint(cards_endpoint), type=List[ScryCard])
msgspec.ValidationError: Invalid enum value 'promo' - at `$[92501].frame_effects[0]`
🔴 ERROR❯ mtg-ssm --version                                
2.6.7
``````
Using the option `--seperate-promos` has no affect on the error.

**Comment by WishMakers0** [comment]
Actually got another one trying it today.  Same issue, except at the end...
```
File "C:\Python312\Lib\site-packages\mtg_ssm\scryfall\fetcher.py", line 78, in scryfetch
    cards_data = msgspec.json.decode(_fetch_endpoint(cards_endpoint), type=List[ScryCard])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Invalid enum value 'spree' - at `$[300].frame_effects[0]`
```
So I guess _two_ small fixes are needed now.  Applied the same fix as your PR as well as adding `SPREE = 'spree'` to models.py and it worked just fine.

**Comment by gwax** [comment]
This should be fully fixed as of right now
